version: 2.1
jobs:
  compilation_et_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --user --no-cache-dir -r requirements.txt
      - run:
          name: Run tests
          command: python3 manage.py test

  build_push_docker_image:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKERHUB_PSEUDO
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build -t $DOCKERHUB_PSEUDO/orange-county-lettings:$CIRCLE_SHA1 .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_PSEUDO --password-stdin
            docker push $DOCKERHUB_PSEUDO/orange-county-lettings:$CIRCLE_SHA1

  build_push_heroku:
    machine: true
    steps:
      - checkout
      - run:
          name: build and deploy image to build_push_heroku
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            HEROKU_API_KEY=$HEROKU_API_KEY heroku container:login
            HEROKU_API_KEY=$HEROKU_API_KEY heroku apps | grep $HEROKU_APP_NAME && echo "app already exist" || heroku apps:create $HEROKU_APP_NAME
            HEROKU_API_KEY=$HEROKU_API_KEY heroku container:push web -a=$HEROKU_APP_NAME
            HEROKU_API_KEY=$HEROKU_API_KEY heroku container:release -a $HEROKU_APP_NAME web

workflows:
  test_build_deploy:
    jobs:
      - compilation_et_test:
          context: orangeCountyLetting
      - build_push_docker_image:
          context: orangeCountyLetting
          requires:
            - compilation_et_test
          filters:
              branches:
                only:
                  - main
      - build_push_heroku:
          context: orangeCountyLetting
          requires:
            - build_push_docker_image
          filters:
              branches:
                only:
                  - main


