version: 2.1
orbs:
  docker: circleci/docker@1.5.0
jobs:
  compilation_et_test:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install --user --no-cache-dir -r requirements.txt
      - run:
          name: Run tests
          command: python3 manage.py test

  build_push_docker_image:
    docker:
      - image: circleci/python:3.9
        auth:
          username: $DOCKERHUB_PSEUDO
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build docker image
          command: |
            docker build -t $DOCKERHUB_PSEUDO/orange-county-lettings:$CIRCLE_SHA1 .
            docker push $DOCKERHUB_PSEUDO/orange-county-lettings:$CIRCLE_SHA1

workflows:
  test_build_deploy:
    jobs:
      - compilation_et_test:
          context: orangeCountyLetting
      - build_push_docker_image:
          context: orangeCountyLetting
          requires:
            - compilation_et_test


